### ISSUE TITLE
Artifacts and other Issues with latest update

### ISSUE THREAD

**Issue by bawigga** [karelvuong/fox#18]
Just got a notice this morning when I started Sublime text that there was an update to my theme. So I restarted and now it looks like this:

![screenshot 2015-02-26 11 21 42](https://cloud.githubusercontent.com/assets/7358/6397373/d73e7158-bda9-11e4-97a0-a1ed923da65e.png)
![screenshot 2015-02-26 11 22 35](https://cloud.githubusercontent.com/assets/7358/6397374/d73f52d0-bda9-11e4-82df-1da32066b986.png)

Happy to provide any other information you need.

**Comment by rtgibbons** [comment]
I'm seeing similar issues 

https://www.dropbox.com/s/9gy3p64u4wz9mzx/Screenshot%202015-02-26%2010.30.55.png?dl=0

**Comment by rtgibbons** [comment]
BTW, i'm Dev Channel build 3071

**Comment by rtgibbons** [comment]
Found my issue. I was use Themr; my theme was set to 


	"theme": "fox.dark.sublime-theme"

Unsetting the fox theme, and reselecting it set it to 


	"theme": "Fox.sublime-theme"

**Comment by bawigga** [comment]
That fixes it for me also. 

The README in the repo still has the old theme under the activation settings.

**Comment by karelvuong** [comment]
@rtgibbons is right. 

The issue outlined in #16 was due to the Theme name having a period in it: `fox.dark.sublime-theme`. It looks like Sublime is not a fan of having theme names having periods in them so parts of the theme were incomplete. So, I renamed it!

Changing the theme name to `Fox.sublime-theme` will fix issue.
